### ISSUE TITLE
Latex with punctuation

### ISSUE THREAD

**Issue by riverliway** [3b1b/3Blue1Brown.com#100]
The formatting for the article won't insert a line break between a word and its ending punctuation. However, it will place a line break between a latex formula and ending punctuation. (Below the question mark is on a new line)

![image](https://user-images.githubusercontent.com/82117023/122806478-38c44b00-d27f-11eb-8c90-2c3e113418d2.png)

I could just reword the sentence to make it not push the punctuation down, but is there a way to have the code group a latex equation with its ending punctuation?

**Comment by vincerubinetti** [comment]
This should be able to be be fixed by forcing the Katex `.base` css class to the `display: inline` (default for a `<span>`), instead of the `display: inline-block` that Katex sets it to.

Here's a demo: https://jsfiddle.net/tcjhv01e/10/
Try commenting out the `inline-block` line in the css.

However this may mess up the layout of other math unexpectedly. Thorough testing should be done before doing this.

**Comment by vincerubinetti** [comment]
Also:

> I could just reword the sentence to make it not push the punctuation down

This would work when the page column is full width, but on mobile or smaller screens, the wrap location will be different. Wouldn't be possible to write it such that it breaks nicely on all screen sizes. So issue needs to be fixed at its root.

Another solution could be to include the punctuation in the equation itself.

**Comment by riverliway** [comment]
I think the solution to include the punctuation inside the latex equation is probably the right way to go here.
