### ISSUE TITLE
Choose backend website hosting

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#15]
GitHub pages is a free web hosting service that can host static things like images, html websites, etc. That's (so far) what we're using to host this website itself and its images/assets.

But we'll need more robust (paid) website hosting for other purposes:

1. GitHub pages could theoretically host all the lesson images and videos, but since it's free, there are storage limits that we'll likely run up against
2. We can't run more dynamic things on GitHub pages, like: hosting an email address, PHP scripts for email forms, Google Captcha services, etc.

Homework for Grant:

Find a website hosting service. I use Inmotion Hosting. Run your choices by me to make sure it has the functionality we'll need, but most popular services should be fine.

**Comment by vincerubinetti** [comment]
https://vercel.com/docs/platform/limits

**Comment by 3b1b** [comment]
I started looking into it, but honestly, I'm probably the least well-equipped of all of us to make this decision.  I looked at vercel a bit, and it seems fine, but I really have no good feel for how to compare it with other options, or even what the full space of other options is.  What I want is:

- Simple to maintain
- Scales easily so we don't have to worry about things breaking if there's an influx of traffic
- No needless costs.  If a service offers meaningfully better simplicity and scalability with a higher price tag than other options, we should go with it, but if possible we should avoid paying for features we won't use.

This is something I'm abundantly happy to outsource.  If you're not sure, I can find others to ask and go with their recommendation, but otherwise, I'm happy to just do whatever you tell me will work.

**Comment by vincerubinetti** [comment]
Btw when I've label things as "homework" for you, I just meant that we'll need you to do some action (like make an api key) or make a final judgement call. We can still help you with these decisions and actions.

Are you looking to decide on this sooner rather than later to start hosting the lesson images/videos? If so I can put it as higher priority and maybe we can have a chat in the next few days.

**Comment by DevParapalli** [comment]
If you don't mind my suggestion, 

<https://www.netlify.com/>

> An intuitive Git-based workflow and powerful serverless platform to build, deploy, and collaborate on web apps

Can be attached to Git Repositories, Builds using your custom tools, contains Form Submissions, and additionally, has Netlify Functions

> Deploy server-side code that works as API endpoints, runs automatically in response to events, or processes more complex jobs in the background. 

Please see, <https://www.netlify.com/products/functions/> and <https://www.netlify.com/products/forms/>

<details>
<summary>Personal Opinion</summary>
I have been using this for hosting my own sites, the workflow is very similar to github-pages, you just write a netlify.toml file with the required data, setup the functions and the site is deployed if everything checks out, You can test branches, roll back to a previous deploy, and I think it has decent team integration. 100 (Valid) Form Submissions, Normal Functions (125k invocations) are present in the free plan. See <https://www.netlify.com/pricing/> for more info.
</details>

**Comment by vincerubinetti** [comment]
Thanks @DevParapalli. We're actually using Netlify right now for our pull request previews. I've used it a lot in the past and liked it. We're considering moving to a newer and a little bit cleaner service called Vercel which seems to be able to do the same things and more.

**Comment by KurtBruns** [comment]
Closing because related to #47
