### ISSUE TITLE
Custom Lesson Thumbnail

### ISSUE THREAD

**Issue by kurtbruns** [3b1b/3Blue1Brown.com#158]
Allow authors to specify a custom thumbnail for a lesson. For example, when splitting a lesson into two parts it makes some sense to specify a different thumbnail for one of the lessons.

**Comment by 3b1b** [comment]
However we do this, we should cleanly abstract out the functionality of taking a lesson id and returning a thumbnail image since that's used in several different places.

**Comment by PullJosh** [comment]
As part of this change, I'm switching from using regular to high resolution thumbnail images, because it's helpful to use the same thumbnail everywhere and the high res one is better as the placeholder for before you click to play a video.

```diff
- https://img.youtube.com/vi/<video id>/hqdefault.jpg
+ https://img.youtube.com/vi/<video id>/maxresdefault.jpg
```

But two videos, [the first Q&A](https://www.youtube.com/watch?v=Qe6o9j4IjTo) and [256 bit security](https://www.youtube.com/watch?v=S9JGmA5_unY), [don't](https://img.youtube.com/vi/Qe6o9j4IjTo/maxresdefault.jpg) [have](https://img.youtube.com/vi/S9JGmA5_unY/maxresdefault.jpg) high res thumbnails available.

Is there an easy way to trigger YouTube to regenerate these? (If not, we can manually include them using the very feature this issue is all about.)

**Comment by 3b1b** [comment]
I imagine reuploading them to YouTube should fix it, so I can do that.

**Comment by PullJosh** [comment]
@kurtbruns This is implemented now! You can see the testbed lesson for an example of how to use it. It's just a `thumbnail` property in the frontmatter that points to the image, the same way you point to images using `<Figure>`.

(You'll need to merge changes from `main` into your own branch, of course.)
