### ISSUE TITLE
Manim-like interactive animations

### ISSUE THREAD

**Issue by hugo-s29** [3b1b/3Blue1Brown.com#194]
Hello,

I've been working for the past two months on [an animation engine](https://github.com/hugo-s29/manim-web). It's able to create both interactive and non-interactive animations in a Manim-like way.

Unlike Manim, `Manim web` is written in Dart, but it's very similar to Python. Dart can be compiled both to JavaScript and to a native app.

I've added [some examples](https://hugo-s29.github.io/manim-web/) like an interactive Fourier Transform animation. The code for these examples is available [here](https://github.com/hugo-s29/manim-web/tree/master/example).

It's not as evolved as Manim or ManimCommunity, but the project is open-source. So, everyone can contribute.

**Comment by PullJosh** [comment]
This is a really awesome tool! You probably already saw, but in the days since you posted this, Grant announced the [SoME1 competition](https://www.youtube.com/watch?v=ojjzXyQCzso), and it certainly seems like you would be a good fit. Definitely watch that video; it could be an excellent opportunity to put your animation engine to good use. 😉

I am thrilled to see what kind of interactive, animated explanation you might be able to put together.
