### ISSUE TITLE
Some related info

### ISSUE THREAD

**Issue by PGTBoos** [3b1b/3Blue1Brown.com#331]
Your article reminded me of something. Once many years ago i ínvented 'prime pyramids',  simple put 1 at the top next row 123 then 45678  and so on, i had a sudden visual insight that it would reveal a pattern, and it sure did, i got overwhelmed by all kinds of people who were into with interest in primes, some long debates too, as to me it was strange that i had this visual thought in flash, but eventually it led lots of discussion as i then 'believed' 1 is prime to ( i kinda still do but that's not the topic), i felt lucky that a half year later people 'discovered' Umlam spiral, so my mailbox flood stopped. essentially though the romans already new that (mod 6) +1 -1 has a high chance of being a prime, for the rest its just the grid we do this on. In my case the pyramids one had rich straight lines.

After the little discovery i was kind of wondered if nature has discovered primes as well, in physics or biologie  like ( https://www.nextbigfuture.com/2018/09/patterns-found-in-prime-numbers.html ) after that I mainly wondered if you take a bunch of prime numbers are they ideally a hard problem for compression? ( the entropy of their distribution ) a far fetched topic, though there is information theory too, and i wasn't able to answer that question.  If you can answer that, there might be a place for it in physics/math too.

**Comment by vincerubinetti** [comment]
Thanks for your comments!

Since this isn't really a bug or feature request with the website itself, it probably makes sense for this to be a comment or discussion. [I think we got rid of Disqus](https://github.com/3b1b/3Blue1Brown.com/issues/107) (the ability to post a public comment on a particular lesson). @3b1b perhaps you could enable Discussions in this repo for things like this?
