### ISSUE TITLE
Switch to Hugo?

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#34]
https://gohugo.io/hosting-and-deployment/

@KurtBruns , would be good if you could list some bullet points of things you like about it. I've personally gotten frustrated with Jekyll more than once, I just chose it because I thought it would be easier for Grant to maintain in the future.

Hugo does seem to have a "jekyll import" function that hopefully works nicely.

**Comment by KurtBruns** [comment]
Ok, I like Hugo for a lot of reasons.

Hugo is fast, easy to install, feature rich, actively maintained and has good documentation.

One of my favorite features is [Hugo Pipes](https://gohugo.io/hugo-pipes/) which can process SCSS, Typescript, SVGs, etc located in an `assets` directory in the build step. For long term development on the site, this results in old assets automatically being removed. It also makes it so you can easily serve un-minified assets for local development and then have minified assets for production.

The content structure and templating is very similar to Jekyll with collections and taxonomies. Instead of liquid components for custom markdown goodies, Hugo has [shortcodes](https://gohugo.io/content-management/shortcodes/). Writing custom short codes is straightforward and some of the built-in shortcodes such as the [tweet display](https://gohugo.io/content-management/shortcodes/#example-tweet-display) might be of use.

If you have any particular pain points with how `Jekyll` does things for templating or content organization, I might be able to address how Hugo is different.

If I think of anything else I will add it.

**Comment by KurtBruns** [comment]
Another thing I thought of over the weekend:

Hugo has a number of [Custom Output Formats](https://gohugo.io/templates/output-formats/) that allow for content to be output in another format. For example, a collection of pages can be output as JSON for a search index.

**Comment by vincerubinetti** [comment]
I will say, over the last year I've grown weary of Jekyll's limitations. Actually, I'm more frustrated with Liquid. Doing anything more than extremely basic templating is often verbose, obtuse, and frustrating to debug. It's like we need a little more than a static site generator, more like a static+ site generator. And that seems to be what Hugo is as far as I can tell.

For now we have to proceed with Jekyll, but if I get free time I'll try out Hugo's "Jekyll import" feature. Maybe it will just work perfectly. Regardless, the hardest part of building the site is getting the design right, which we're doing upfront, and is portable to any framework.

**Comment by KurtBruns** [comment]
I've been poking around more in Jekyll's Docs.

A feature that Hugo has for organizing content is [Hugo Page Bundles](https://gohugo.io/content-management/page-bundles/) related to #40
