### ISSUE TITLE
Automatically size figure to always look good and fullscreen on click

### ISSUE THREAD

**Issue by vincerubinetti** [3b1b/3Blue1Brown.com#76]
Right now we're leaving it up to the author to size each image/video manually, eg. `width: 60%` or `height: 300px`. Maybe, to enforce consistency, we can figure out some algorithm that automatically sizes it such that it always looks good and consistent. We could always keep the manual sizing there for special cases, I suppose.

@3b1b thoughts?

Also, for the sake of detailed figures, we could have the image/video pop out and become full screen on click. Though I don't recommend making a figure so detailed that this is absolutely necessary, because if it has that much fine detail, it won't be legible on mobile even when full screen. Though, still a nice option to have. Browsers already have built-in controls for fullscreening videos so we'd only need to implement it for images.

**Comment by 3b1b** [comment]
I just brought this up today, actually. I think we should definitely figure out the right algorithm, and in a perfect world there would never be a hard-coded width in the markdown. The basic idea will probably be that something which is tall enough to eat up too much of the screen height should be narrowed down.  It may be the case we'd handle images which are landscape vs. portrait differently.

As to popouts, if it's abundantly easy that seems nice, but to your point, since we should be avoiding that level of detail anyway, consider it low priority.
